	<!-- Copyright Start -->
	<div class="copyright">
	    <div class="container">
	        <div class="row">
                <div class="col-md-5 copyright-area">
					<p class="inner-link-list">
					</p>
	                <p class="copyright-text">
	                    Copyright © 2016 WSC All Rights Reserved.&nbsp;&nbsp;&nbsp;&nbsp;沪ICP备XXXXX号-20
	                </p>
	            </div>
	        </div>
	    </div>
	</div>
	<!-- Copyright End-->