<head>
    <title>Wsc Blog</title>

    <!-- Meta Start-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <meta name="application-name" content="WscBlog" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="keywords" content="WscBlog, Demo">
    <meta name="description" content="A demo blog">
    <meta name="author" content="ChenFei">
    <meta name="applicable-device" content="pc,mobile">
    <!-- Meta End-->
    	
    <!-- Icon Start-->
    <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link href="/favicon.ico" rel="icon" type="image/x-icon">
    <!-- Icon End-->
    
    <!-- CSS Start-->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/styles.css">
    <link rel="stylesheet" href="/css/icon.css">	
    <!-- CSS End-->
</head> 