	<!-- Top Start -->
	<div class="top visible-lg visible-md">
	    <div class="container">
	        <div class="row">
				<!-- Top Menu Start -->
	            <div class="col-md-12">
	            	<div style="margin-top:10px;float:left;">
	            		<a href="/">A WSC Demo Blog</a>
	            	</div>
					
					<?php if ($user = $this->session->get('auth')) { ?>					
	            	<div>
						<ul class="toolbar pull-right">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle username" data-toggle="dropdown">
									<span class="">欢迎您：<?php echo $user['name']; ?></span>
								</a>
								<a href="/user/logout" rel="nofollow">
									<!-- <i class="pull-right fa fa-sign-out"></i> --> 退出
								</a>
							</li>
						</ul>
					</div>
					<?php } else { ?>	
	            	<div>
		                <ul class="list-unstyled top-data">
		                	<li>
						    	<a href="/articles/add" class="btn-u btn-u-purple hover-effect" rel="nofollow">
									<i class="fa fa-pencil-square-o"></i>我要投稿
								</a>
		                	</li>
		                    <li>
		                    	<a href="/user/login" class="btn-u btn-u-orange hover-effect" rel="nofollow">
		                    		<i class="fa fa-sign-in"></i>登录
		                    	</a>
		                    </li>
		                    <li>
		                    	<a href="/user/register" class="btn-u btn-u-green hover-effect" rel="nofollow">
		                    		<i class="fa fa-user"></i>注册
		                    	</a>
		                    </li>
		                </ul>
	            	</div>										
					<?php } ?>						
	            </div>
	            <!-- Top Menu End -->
	        </div>
	    </div>
	</div>
	<!-- Top end -->