<?$pagerBaseQuery = null;?>
<?if($pager->total_pages > 1):?>
<ul class="pagination">
    <?if($pager->current > 2):?>
    <li><a href="<?=$this->escaper->escapeHtmlAttr($this->tag->uri($pagerUrl, array('page' => $pager->first), $pagerBaseQuery))?>">«</a></li>
    <?endif?>
    <?if($pager->current > 1):?>
    <li><a href="<?=$this->escaper->escapeHtmlAttr($this->tag->uri($pagerUrl, array('page' => $pager->before), $pagerBaseQuery))?>">prev</a></li>
    <?endif?>
    <?if(0 && $pager->prev_skip):?>
    <li><a href="javascript:;">...</a></li>
    <?endif?>
    <?if($pager->prev_range):?>
    <?foreach($pager->prev_range as $page):?>
    <li><a href="<?=$this->escaper->escapeHtmlAttr($this->tag->uri($pagerUrl, array('page' => $page), $pagerBaseQuery))?>"><?=$page?></a></li>
    <?endforeach?>
    <?endif?>
    <li class="active"><a href="<?=$this->escaper->escapeHtmlAttr($this->tag->uri($pagerUrl, array('page' => $pager->current), $pagerBaseQuery))?>"><?=$pager->current?></a></li>
    
    <?if($pager->next_range):?>
    <?foreach($pager->next_range as $page):?>
    <li><a href="<?=$this->escaper->escapeHtmlAttr($this->tag->uri($pagerUrl, array('page' => $page), $pagerBaseQuery))?>"><?=$page?></a></li>
    <?endforeach?>
    <?endif?>
    <?if(0 && $pager->next_skip):?>
    <li><a href="javascript:;">...</a></li>
    <?endif?>
    <?if($pager->next && $pager->current < $pager->last):?>
    <li><a href="<?=$this->escaper->escapeHtmlAttr($this->tag->uri($pagerUrl, array('page' => $pager->next), $pagerBaseQuery))?>">next</a></li>
    <?endif?>
    <?if($pager->current < $pager->last):?>
    <li><a href="<?=$this->escaper->escapeHtmlAttr($this->tag->uri($pagerUrl, array('page' => $pager->last), $pagerBaseQuery))?>">»</a></li>
    <?endif?>
</ul>
<?endif?>
