<!DOCTYPE html>
<!--[if IE 7]> <html lang="en" class="ie7"> <![endif]-->  
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
<!--[if !IE]><!--> <html lang="zh"> <!--<![endif]-->  

<?php $this->partial("head") ?>

<body>
	<?php $this->partial("header") ?>
	<?= $this->getContent() ?>
	<?php $this->partial("copyright") ?>
</body>

</html>