	<!-- Content Start -->
	<div class="contents">
		<div class="container">
		    <div class="row">
		        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 margin-bottom-30">
					
				    <form method="post" action="/user/login">
				        <div class="reg-header">
							<h2>登录</h2>							
				        </div>
		                <label for='userName'>用户名：<span class="color-red">*</span></label>
						<input name="name" class="form-control margin-bottom-20" placeholder="请输入用户名" maxlength="100" type="text" id="userName">
		                <label for='userPw'>密码：<span class="color-red">*</span></label>
						<input name="pw" class="form-control margin-bottom-20" placeholder="密码" type="password" id="userPw">
	                    <div class="col-lg-6 text-right">  
							<input type='submit' value='登陆'>
	                    </div>						
					</form>
					
		        </div>
		    </div>
		</div>
	</div>
	<!-- Content End -->