	<!-- Content Start -->
	<div class="contents">
		<div class="container">
		    <div class="row">
		        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 margin-bottom-30">
					
				    <form method="post" action="/user/register">
				        <div class="reg-header">
							<h2>注册新用户</h2>							
				        </div>
						<p>演示用，只验证了两次密码相同，省略了注册邮箱，验证邮件，各项验证等</p>
		                <label for='userName'>用户名：<span class="color-red">*</span></label>
						<input name="name" class="form-control margin-bottom-20" placeholder="请输入用户名" maxlength="100" type="text" id="userName">
		                <label for='pw'>密码：<span class="color-red">*</span></label>
						<input name="pw" class="form-control margin-bottom-20" placeholder="密码" type="password" id="userPw">
		                <label for='pw2'>重复密码：<span class="color-red">*</span></label>
						<input name="pw2" class="form-control margin-bottom-20" placeholder="重复密码" type="password" id="userPw">						
	                    <div class="col-lg-6 text-right">  
							<input type='submit' value='注册'>
	                    </div>						
					</form>
						
		        </div>
		    </div>
		</div>
	</div>
	<!-- Content End -->